### ISSUE TITLE
docker部署支持问题？

### ISSUE THREAD

**Issue by KormiMeiko** [ybw2016v/mkhost#1]
大佬，有没有docker部署的misskey可以用哒

**Comment by ybw2016v** [comment]
这个应该和部署方式关系不大，只要能正常连接postgresql即可，我用这个脚本的时候就是用ssh把postgresql的端口转发的本地。

如果用docker部署的，可以临时改一下`docker-compose.yml`文件，或者用其他方式把postgresql的端口暴露出来即可，数据库的密码等信息在`.config/docker.env`里面。
